#!/bin/sh
vx check dunst >/dev/null || exit 1
online || exit 1
cd ~
exec qutebrowser --qt-flag enable-gpu-rasterization --qt-flag enable-oop-rasterization --qt-flag enable-accelerated-video-decode 2>&1
