listen_addresses = ['127.0.0.1:53']
ipv4_servers = true
ipv6_servers = false
doh_servers = true
dnscrypt_servers = true
block_ipv6 = true
ignore_system_dns = true
bootstrap_resolvers = ['9.9.9.9:53', '8.8.8.8:53', '1.1.1.1:53']
server_names = ['google', 'cloudflare', 'hdns', 'libredns', 'bcn-doh', 'dnscrypt.be', 'meganerd']
forwarding_rules = 'athonet-rules.txt'

[sources]
  [sources.'public-resolvers']
    urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/public-resolvers.md',
            'https://download.dnscrypt.info/resolvers-list/v3/public-resolvers.md']
    minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
    cache_file = '/var/cache/dnscrypt-proxy-public-resolvers.md'
