export PATH=~/env/bin:/usr/bin
export LANG=en_US.UTF-8
export TERM=xterm-256color

export XDG_DESKTOP_DIR=$HOME
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.data
export XDG_RUNTIME_DIR=/tmp/run-$(id -u)

export EDITOR=vi
export BROWSER=b
export PAGER=bat

xdg-mkdirs
[ -f ~/.asdf/asdf.sh ] && source ~/.asdf/asdf.sh
