#
# defaults
#
export PATH=~/env/bin/override:~/env/bin:/usr/bin:/usr/bin/core_perl:/usr/bin/vendor_perl
export LANG=en_US.UTF-8

export XDG_DESKTOP_DIR=$HOME
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.data
