""
" GUI
""

set guioptions=gimrLtT "Opciones por defecto
set guioptions+=f "Para que gvim no se vaya a background
set guioptions+=c "Para las confirmaciones sean en la barra de estado
set guioptions-=m "Remueve el menu

""
" keyboard shortcuts
""

"CTRL-X cortar
vnoremap <silent> <C-X> "*x 

"CTRL-C copiar
vnoremap <C-C> "*y

"CTRL-V pegar
noremap <C-V> "*p
inoremap <C-V> <C-O>"*p

"CTRL-S guarda tambien en modo Insert
noremap <C-S> :update<CR>
vnoremap <C-S> <C-C>:update<CR>
inoremap <C-S> <C-O>:update<CR>

"CTRL-Z Deshacer
noremap <C-Z> u
inoremap <C-Z> <C-O>u

"CTRL-Y Rehacer
noremap <C-Y> <C-R>
inoremap <C-Y> <C-O><C-R>

"CTRL-A Seleccionar todo en cualquier modo
noremap <C-A> gggH<C-O>G
inoremap <C-A> <C-O>gg<C-O>gH<C-O>G
cnoremap <C-A> <C-C>gggH<C-O>G
onoremap <C-A> <C-C>gggH<C-O>G
snoremap <C-A> <C-C>gggH<C-O>G
xnoremap <C-A> <C-C>ggVG
