#! /bin/bash

#
# autologin
#
i3lock &

#
# xorg
#
xrdb -merge $HOME/env/xinit.d/Xresources
xsetroot -solid "#000000" &
xset b 0 &
setxkbmap -layout us -variant altgr-intl &
#synclient MinSpeed=0.8 MaxSpeed=4.0 &
#synclient TapButton1=-1 TapButton2=-1 TapButton3=-1 &

#
# HW
#
start-pulseaudio-x11 &

#
# desktop
#
supervise.sh xsettingsd &
supervise.sh sxhkd &
supervise.sh dunst &
supervise.sh termite -e tmux &
supervise.sh copyq &

#
# user specific config
#
if [ -x ~/env/xinit.d/$USER.xprofile ]; then
    ~/env/xinit.d/$USER.xprofile
fi
