#! /bin/bash

#
# autologin
#
i3lock &

#
# xorg
#
xrdb $HOME/env/xinit.d/xresources
xsetroot -solid "#000000" &
xset b 0 &
autorandr -c &
#setxkbmap -layout us -variant altgr-intl &
#synclient MinSpeed=0.8 MaxSpeed=4.0 &
#synclient TapButton1=-1 TapButton2=-1 TapButton3=-1 &

#
# desktop
#
supervise.sh sxhkd &
supervise.sh dunst &
supervise.sh alacritty -e tmux &
supervise.sh clipmenud &
#supervise.sh batsignal &

#
# user specific config
#
if [ -f ~/env/xinit.d/$USER.xprofile ]; then
    source ~/env/xinit.d/$USER.xprofile
fi
